import jsPDF from "jspdf";
import { useState } from "react";

export default function DownloadReport({ data }) {
  const [isHovered, setIsHovered] = useState(false);

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    const addText = (text, x, fontSize, style = "normal", color = [10, 10, 10]) => {
      doc.setFontSize(fontSize);
      doc.setFont("helvetica", style);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, pageWidth - x - 20);
      lines.forEach((line) => {
        if (y > 275) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, x, y);
        y += fontSize * 0.5;
      });
    };

    const addSpacer = (h = 8) => { y += h; };
    const addLine = () => {
      doc.setDrawColor(229, 229, 229);
      doc.line(15, y, pageWidth - 15, y);
      y += 5;
    };

    // Title
    addText("Resume Analysis Report", 15, 22, "bold", [0, 113, 227]);
    addSpacer(12);

    // Candidate info
    if (data.candidate_name) {
      addText(`Candidate: ${data.candidate_name}`, 15, 12, "bold");
      addSpacer(4);
    }
    if (data.detected_role) {
      addText(`Detected Role: ${data.detected_role}`, 15, 11, "normal", [100, 100, 100]);
      addSpacer(4);
    }
    addLine();

    // Overall Score
    addText(`Overall Score: ${data.overall_score ?? "N/A"} / 100`, 15, 16, "bold");
    addSpacer(6);

    // Summary
    if (data.summary) {
      addText(data.summary, 15, 10, "normal", [80, 80, 80]);
      addSpacer(6);
    }
    addLine();

    // Section Scores
    if (data.section_scores) {
      addText("Section Scores", 15, 14, "bold");
      addSpacer(6);
      const labels = {
        contact_info: "Contact Info",
        professional_summary: "Professional Summary",
        work_experience: "Work Experience",
        education: "Education",
        skills: "Skills",
        formatting: "Formatting",
      };
      Object.entries(labels).forEach(([key, label]) => {
        const score = data.section_scores[key] ?? "N/A";
        addText(`• ${label}: ${score}/100`, 18, 10);
        addSpacer(2);
      });
      addSpacer(4);
      addLine();
    }

    // Skills Analysis
    if (data.skills_analysis) {
      addText("Skills Analysis", 15, 14, "bold");
      addSpacer(6);
      const sa = data.skills_analysis;
      if (sa.technical_skills?.length) {
        addText(`Technical: ${sa.technical_skills.join(", ")}`, 18, 10);
        addSpacer(3);
      }
      if (sa.soft_skills?.length) {
        addText(`Soft Skills: ${sa.soft_skills.join(", ")}`, 18, 10);
        addSpacer(3);
      }
      if (sa.certifications?.length) {
        addText(`Certifications: ${sa.certifications.join(", ")}`, 18, 10);
        addSpacer(3);
      }
      if (sa.missing_key_skills?.length) {
        addText(`Missing: ${sa.missing_key_skills.join(", ")}`, 18, 10, "normal", [255, 59, 48]);
        addSpacer(3);
      }
      addSpacer(4);
      addLine();
    }

    // Improvements
    if (data.improvements?.length) {
      addText("Key Improvements", 15, 14, "bold");
      addSpacer(6);
      data.improvements.forEach((item, i) => {
        const priority = (item.priority ?? "Medium").toUpperCase();
        const issue = item.issue ?? item.description ?? "";
        const fix = item.fix ?? "";
        addText(`${i + 1}. [${priority}] ${issue}`, 18, 10, "bold");
        addSpacer(2);
        if (fix) {
          addText(`   Fix: ${fix}`, 22, 9, "normal", [80, 80, 80]);
          addSpacer(3);
        }
      });
      addSpacer(4);
      addLine();
    }

    // Action Plan
    if (data.action_plan?.length) {
      addText("Action Plan", 15, 14, "bold");
      addSpacer(6);
      data.action_plan.forEach((step, i) => {
        const text = typeof step === "string" ? step : step.description ?? step.text ?? JSON.stringify(step);
        addText(`${i + 1}. ${text}`, 18, 10);
        addSpacer(3);
      });
    }

    // Footer
    addSpacer(10);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text("Generated by ResumeAI", pageWidth / 2, 290, { align: "center" });

    doc.save("resume-analysis-report.pdf");
  };

  return (
    <div style={{
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      zIndex: 100,
      background: 'rgba(10, 14, 26, 0.9)',
      backdropFilter: 'blur(12px)',
      WebkitBackdropFilter: 'blur(12px)',
      borderTop: '1px solid var(--border)',
      padding: '14px 48px',
      display: 'flex',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 16
    }}>
      <div className="hidden md:block" style={{ fontSize: 14, color: 'var(--text-secondary)' }}>
        Analysis complete · {data.candidate_name || 'Candidate'}
      </div>
      
      <button
        onClick={generatePDF}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        style={{
          background: isHovered ? 'var(--accent)' : 'transparent',
          border: '1px solid var(--accent)',
          color: isHovered ? 'white' : 'var(--accent)',
          padding: '10px 24px',
          borderRadius: 'var(--radius-md)',
          fontSize: 14,
          fontWeight: 600,
          fontFamily: 'inherit',
          cursor: 'pointer',
          transition: 'all 0.2s',
          boxShadow: isHovered ? '0 4px 20px rgba(79,142,247,0.3)' : 'none'
        }}
      >
        ↓ Download PDF Report
      </button>
    </div>
  );
}
